services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - tgbot
    
  php:
    image: php:8.5.3-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - tgbot

networks:
  tgbot: